### PR TITLE
Upgrade packages, generate UMD & ES packages, remove accessibility warnings & convert to a SvelteKit based component.

### PR DESCRIPTION
**Pull request by eraviart**

### CODE REVIEW

**Comment by nosovk** [comment]
@tanhauhau probably merging that would close https://github.com/tanhauhau/svelte-json-tree/issues/7
which appears if you use that package in svelte-kit

**Comment by FractalHQ** [comment]
@tanhauhau Hey man!  Anything stopping you from merging this?  It's doing a number on my logs 😅

Screenshot 2021-07-08 at 12 35 26 PM

**Comment by tanhauhau** [comment]
Thanks :)

**Comment by eraviart** [comment]
To generate package , you need to do:
```shell
npm run package
```
And to publish the package to npm, you need to publish the content of the `package` directory:
```shell
cd package/
npm publish --access=public
```

**Pull request merged**
